---
name: Test Download Artifacts Action

on:
  workflow_dispatch:
    inputs: {}

jobs:
  download-latest:
    name: Download Latest
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579

      - name: Download
        uses: ./download-artifacts
        with:
          workflow: upload.yml
          artifacts: artifact
          path: artifact

      - name: Test
        run: cat artifact/sha | grep $GITHUB_SHA


  download-branch:
    name: Download BRANCH
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579

      - name: Download
        uses: ./download-artifacts
        with:
          workflow: upload.yml
          artifacts: artifact
          path: artifact
          branch: master

      - name: Test
        run: cat artifact/sha | grep $GITHUB_SHA


  download-pr:
    name: Download Pull Request
    runs-on: ubuntu-20.04
    if: github.ref != 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579

      - name: Download
        uses: ./download-artifacts
        with:
          workflow: upload.yml
          artifacts: artifact
          path: artifact
          pr: ${{github.event.pull_request.number}}

      - name: Test
        run: cat artifact/sha | grep $GITHUB_SHA


  download-all:
    name: Download All
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579

      - name: Download
        uses: ./download-artifacts
        with:
          workflow: upload.yml

      - name: Test
        run: |
          cat artifact1/sha1 | grep $GITHUB_SHA
          cat artifact2/sha2 | grep $GITHUB_SHA


  download-multiple:
    name: Download Multiple
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579

      - name: Download
        uses: ./download-artifacts
        with:
          workflow: upload.yml
          artifacts: 'artifact1,
                 artifact2'

      - name: Test
        run: |
          ls -alth
          cat artifact1/sha1 | grep $GITHUB_SHA
          cat artifact2/sha2 | grep $GITHUB_SHA


  download-wildcard:
    name: Download Wildcard
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579

      - name: Download
        uses: ./download-artifacts
        with:
          workflow: upload.yml
          artifacts: '*.txt'

      - name: Test
        run: |
          ls -alth
          cat artifact1.txt/sha1 | grep $GITHUB_SHA
          cat artifact2.txt/sha2 | grep $GITHUB_SHA


  download-conclusion:
    name: Download Conclusion
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579

      - name: Download
        uses: ./download-artifacts
        with:
          workflow: upload.yml
          artifacts: artifact
          path: artifact
          workflow_conclusion: ''

      - name: Test
        run: cat artifact/sha | grep $GITHUB_SHA
